services:
  nginx:
    container_name: nginx
    image: nginx:1.27
    depends_on:
      - frontend-nextjs
      - backend-springboot
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysqldb:
    image: mysql:8.0-debian
    restart: unless-stopped
    container_name: my-sqldb
    volumes:
      - ./initDB.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=thuanhm
    ports:
      - 3307:3306

  backend-springboot:
    depends_on:
      - mysqldb
    restart: unless-stopped
    container_name: my-backend
    build:
      context: ./appBE
      dockerfile: Dockerfile
    volumes:
      - ./blogStorageBackup/:/blogStorage/

    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/blogapp
    #   - SPRING_DATASOURCE_USERNAME=root
    #   - SPRING_DATASOURCE_PASSWORD=
    #   - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    #   - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    #   - APP_UPLOAD_FILE_BASE_URI=file:///blogStorage/
    #   - APP_JWT_JWT_SECRET_KEY=
    #   - APP_JWT_JWT_VALIDITY_IN_SECONDS=14400
    #   - APP_JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS=86400
    #   - SPRING_MAIL_HOST=smtp.gmail.com
    #   - SPRING_MAIL_PORT=587
    #   - SPRING_MAIL_USERNAME=app.worker365@gmail.com
    #   - SPRING_MAIL_PASSWORD=thdhslkjfqzkmjrj
    #   - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    #   - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
    links:
      - mysqldb
    expose:
      - "8080"
    ports:
      - 8081:8080
  frontend-nextjs:
    container_name: my-frontend
    depends_on:
      - backend-springboot
    build:
      context: ./appFE
      dockerfile: Dockerfile
    restart: unless-stopped
